name: Generate New Commit Message

on:
  pull_request:
    types: [closed]
    branches:
      - master
    # Ensure the pull request was squashed
    # This event does not differentiate between regular close and squash merge
    # Additional checks will be done in the job
    paths-ignore:
      - '**'

jobs:
  generate-commit-message:
    if: github.event.pull_request.merged && github.event.pull_request.merge_commit_sha
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate new commit message
        id: openai
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install openai

      - name: Extract PR author info
        id: extract_pr_info
        run: |
          PR_URL="${{ github.event.pull_request.url }}"
          AUTHOR_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${PR_URL}/merge" | jq -r '.committer')
          AUTHOR_USERNAME=$(echo $AUTHOR_INFO | jq -r '.login')
          AUTHOR_EMAIL=$(echo $AUTHOR_INFO | jq -r '.email')
          echo "::set-output name=username::${AUTHOR_USERNAME}"
          echo "::set-output name=email::${AUTHOR_EMAIL}"

      - name: Generate commit message
        id: commit_message
        run: |
          echo "Generating commit message..."
          export OLD_COMMIT_MESSAGE=$(git log --format=%B -n 1 HEAD)
          export GENERATED_MESSAGE=$(openai api completions.create -e text-davinci-003 --prompt "The current commit message is: \"$OLD_COMMIT_MESSAGE\". Please generate a new commit message:" --max_tokens 100 --api-key ${{ secrets.OPENAI_API_KEY }})
          echo "::set-output name=message::${GENERATED_MESSAGE}"

      - name: Configure Git identity
        run: |
          git config --global user.email "${{ steps.extract_pr_info.outputs.email }}"
          git config --global user.name "${{ steps.extract_pr_info.outputs.username }}"

      - name: Update commit message
        run: |
          git commit --amend -m "${GENERATED_MESSAGE}"
